In [15]:
#Q1.
#a)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array: ", reversed_arr)

#b)
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
f1 = array1.flatten()
f2 = array1.ravel()
print("Flattened arr: ",f1)
print("flattened arr: ",f2)

#c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = np.array_equal(arr1,arr2)
print("Are the two arrays equal? ", comparison)

#d)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent(arr):
  vals, counts = np.unique(arr, return_counts=True)
  max_count = max(counts)
  most_freq = vals[np.argmax(counts)]
  indices = np.where(arr == most_freq)[0]
  return most_freq, indices
freq_x, indices_x = most_frequent(x)
freq_y, indices_y = most_frequent(y)
print("x: Most frequent =", freq_x, ", Indices =", indices_x)
print("y: Most frequent =", freq_y, ", Indices =", indices_y)

#e)
gfg = np.matrix('4, 1, 9; 12, 3, 1; 4, 5, 6')
sum_all = gfg.sum()
sum_rows = gfg.sum(axis=1)
sum_cols = gfg.sum(axis=0)
print("Sum of all elements:", sum_all)
print("Sum row-wise:", sum_rows)
print("Sum column-wise:", sum_cols)

#f)
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
sum_diag = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print("Sum of diagonal elements:", sum_diag)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", inverse)
print("Determinant:", determinant)

#g)
#i)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)
#ii)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("(g.i) Matrix product:\n", product1)
print("(g.i) Covariance:\n", cov1)
print("(g.ii) Matrix product:\n", product2)
print("(g.ii) Covariance:\n", cov2)

#h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
# Inner product
inner_product = np.inner(x, y)
# Outer product (flatten first)
outer_product = np.outer(x.flatten(), y.flatten())
# Cartesian product
cartesian_product = np.array([[i, j] for i in x.flatten() for j in y.flatten()])
print("Inner product:\n", inner_product)
print("Outer product:\n", outer_product)
print("Cartesian product:\n", cartesian_product)


Reversed array:  [5 4 6 3 2 1]
Flattened arr:  [1 2 3 2 4 5 1 2 3]
flattened arr:  [1 2 3 2 4 5 1 2 3]
Are the two arrays equal?  True
x: Most frequent = 1 , Indices = [0 5 7 8]
y: Most frequent = 1 , Indices = [0 1 2]
Sum of all elements: 45
Sum row-wise: [[14]
 [16]
 [15]]
Sum column-wise: [[20  9 16]]
Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001
(g.i) Matrix product:
 [[16 19]
 [26 31]]
(g.i) Covariance:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
(g.ii) Matrix product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
(g.ii) Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner product:
 [[17 52]
 [13 62]]
Outer product:
 

In [23]:
#Q2
# a)
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)
print("Element wise absolute value: ",abs_array)

flattened = array.flatten()
percentile_flat = np.percentile(flattened, [25, 50, 75])
print("Percentile of flattened array:",percentile_flat)
percentile_col = np.percentile(array, [25, 50, 75], axis=0)
percentile_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentile for each row: ",percentile_row)
print("Percentile for each column: ",percentile_col)

mean_col = np.mean(array, axis=0)
mean_row = np.mean(array, axis=1)
median_col = np.median(array, axis=0)
median_row = np.median(array, axis=1)
std_col = np.std(array, axis=0)
std_row = np.std(array, axis=1)
print("Mean Col: ",mean_col)
print("Mean Row: ",mean_row)
print("Median Col: ",median_col)
print("Median Row: ",median_row)
print("Standard Row: ",std_row)
print("Standard Col: ",std_col)
mean_flat = np.mean(flattened)       # Average of all values
median_flat = np.median(flattened)   # Middle value after sorting
std_flat = np.std(flattened)         # Spread of values (std dev)
print("Mean flat: ", mean_flat)
print("Median flat: ", median_flat)
print("Standard flat: ", std_flat)

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)
print("Floor: ",floor_vals)
print("Ceil: ",ceil_vals)
print("Round: ",round_vals)
print("Truncate: ",trunc_vals)

Element wise absolute value:  [[1 2 3]
 [4 5 6]]
Percentile of flattened array: [-3.5 -0.5  2.5]
Percentile for each row:  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Percentile for each column:  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Mean Col:  [-1.5  1.5 -1.5]
Mean Row:  [ 0.66666667 -1.66666667]
Median Col:  [-1.5  1.5 -1.5]
Median Row:  [ 1. -4.]
Standard Row:  [2.05480467 4.78423336]
Standard Col:  [2.5 3.5 4.5]
Mean flat:  -0.5
Median flat:  -0.5
Standard flat:  3.8622100754188224
Floor:  [-2. -2. -1.  0.  1.  1.  3.]
Ceil:  [-1. -1. -0.  1.  2.  2.  3.]
Round:  [-2. -2. -0.  0.  2.  2.  3.]
Truncate:  [-1. -1. -0.  0.  1.  1.  3.]


In [25]:
#Q3
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])
# (i) Sorted array
sorted_array = np.sort(array)
# (ii) Indices of sorted array
sorted_indices = np.argsort(array)
# (iii) 4 smallest elements
smallest_4 = np.sort(array)[:4]
# (iv) 5 largest elements
largest_5 = np.sort(array)[-5:]  # or use: np.partition(array, -5)[-5:]
print("Sorted:", sorted_array)
print("Sorted indices:", sorted_indices)
print("4 smallest:", smallest_4)
print("5 largest:", largest_5)

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# (i) Integer elements only
integers = array[np.floor(array) == array]

# (ii) Float (non-integer) elements only
floats = array[np.floor(array) != array]
print("Integers:", integers)
print("Floats:", floats)


Sorted: [ 10  16  16  52  54  62 453]
Sorted indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]
Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


In [35]:
#Q4
#a)
from PIL import Image
import numpy as np

def img_to_array(path):
    try:
        # Open image
        img = Image.open(path)

        # Convert to numpy array
        img_array = np.array(img)

        # Check if Grey Scale or RGB
        if len(img_array.shape) == 2:  # Grey scale image (2D array)
            print("Grey scale image detected")
            print(f"Image shape: {img_array.shape}")
            # Save as single text file
            np.savetxt("greyscale_image.txt", img_array, fmt='%d')
            print("Saved as: greyscale_image.txt")

        elif len(img_array.shape) == 3:  # RGB image (3D array)
            print("RGB image detected")
            print(f"Image shape: {img_array.shape}")
            # Save each channel separately
            np.savetxt("rgb_image_r.txt", img_array[:,:,0], fmt='%d')
            np.savetxt("rgb_image_g.txt", img_array[:,:,1], fmt='%d')
            np.savetxt("rgb_image_b.txt", img_array[:,:,2], fmt='%d')
            print("Saved as: rgb_image_r.txt, rgb_image_g.txt, rgb_image_b.txt")

        return img_array

    except FileNotFoundError:
        print(f"Error: File not found at path: {path}")
        return None
    except Exception as e:
        print(f"Error processing image: {e}")
        return None


img_array = img_to_array('/content/drive/MyDrive/floweryay.jpeg')
if img_array is not None:
    print(f"Successfully processed image with shape: {img_array.shape}")


RGB image detected
Image shape: (1308, 736, 3)
Saved as: rgb_image_r.txt, rgb_image_g.txt, rgb_image_b.txt
Successfully processed image with shape: (1308, 736, 3)


In [39]:
#4 b)
def load_saved_file(image_type='rgb'):
    try:
        if image_type == 'greyscale':
            # Load single greyscale file
            loaded_array = np.loadtxt("greyscale_image.txt", dtype=int)
            print(f"Loaded greyscale image with shape: {loaded_array.shape}")

        elif image_type == 'rgb':
            # Load three separate RGB channel files and combine
            r_channel = np.loadtxt("rgb_image_r.txt", dtype=int)
            g_channel = np.loadtxt("rgb_image_g.txt", dtype=int)
            b_channel = np.loadtxt("rgb_image_b.txt", dtype=int)

            # Stack channels to recreate RGB image
            loaded_array = np.stack((r_channel, g_channel, b_channel), axis=-1)
            print(f"Loaded RGB image with shape: {loaded_array.shape}")

        return loaded_array

    except FileNotFoundError as e:
        print(f"Error: Could not find saved file(s): {e}")
        return None
    except Exception as e:
        print(f"Error loading file: {e}")
        return None

# Load the saved file (adjust image_type based on your image)
loaded_image = load_saved_file('rgb')  # or 'greyscale' if your image is greyscale

# Verify the loaded data matches original
if loaded_image is not None:
    print("File successfully loaded into Jupyter notebook!")

    # Optional: Display basic statistics
    print(f"Min value: {loaded_image.min()}")
    print(f"Max value: {loaded_image.max()}")
    print(f"Mean value: {loaded_image.mean():.2f}")


Loaded RGB image with shape: (1308, 736, 3)
File successfully loaded into Jupyter notebook!
Min value: 0
Max value: 255
Mean value: 132.03


In [40]:
# Complete workflow
from PIL import Image
import numpy as np

# Step 1: Read and save image
img_array = img_to_array('/content/drive/MyDrive/floweryay.jpeg')

# Step 2: Load saved file back
if img_array is not None:
    # Determine if RGB or greyscale based on original array
    if len(img_array.shape) == 2:
        loaded_array = load_saved_file('greyscale')
    else:
        loaded_array = load_saved_file('rgb')

    # Step 3: Verify data integrity
    if loaded_array is not None and np.array_equal(img_array, loaded_array):
        print("Data integrity verified: Original and loaded arrays are identical")
    else:
        print("Original and loaded arrays differ")


RGB image detected
Image shape: (1308, 736, 3)
Saved as: rgb_image_r.txt, rgb_image_g.txt, rgb_image_b.txt
Loaded RGB image with shape: (1308, 736, 3)
Data integrity verified: Original and loaded arrays are identical
